baseurl = "https://sqh.me/"
title = "宋其翰的博客"
languageCode = "zh-cn"
MetaDataFormat = "toml"
theme = "hugo-theme-yilia"

[params]
	author = "qhsong"
	slogan = "Need a job!"
    animate = true
    avatar="https://www.gravatar.com/avatar/f876c5f1daa51dd2a16a02eb25b4280b?s=128"
    duoshuo="qhsong"
    fancybox= true
    mathjax="false"
    open_in_new=true
    inner_archive=false
    tagcloud=true

[[menu.subnav]]
    Name = "github"
    URL= "https://github.com/qhsong"
[[menu.subnav]]
    Name = "twitter"
    URL = "https://twitter.com/qihansong"
