baseurl = "http://example.com/"
title = "宋其翰的博客"
languageCode = "zh-cn"
MetaDataFormat = "toml"
theme = "liquorice"

[params]
	author = "qhsong"
[[menu.main]]
	name = "about me"
	pre = "<i class='ds'></i>"
	weight = -110
	identifier = "about"
