BaseUrl: "http://sqh.me"
LanguageCode: "zh-cn"
Title: "Aglaus"

Params:
  Author: "Your name."
  DateForm: "Mon, Jan 2, 2006"
  GoogleAnalyticsUserID: "Your ID."
  Facebook: "Your ID."
  Twitter: "Your ID."
  Github: "Your ID."
  ShowRelatedPost: True
  Disqus: "Your Disqus."
  SyntaxHighlightTheme: "solarized_dark.min.css"

Indexes:
  tag: "tags"

permalinks:
  post: /blog/:year/:month/:day/:title/

MetadataFormat: "toml"

